version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:13.8.0-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: npm install
      - run: npm test
